version: '3'
services:
  pcm-http:
    container_name: pcm-http
    image: nginx:1-alpine
    volumes:
      - ./docker/server.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    links:
      - pcm-app
  pcm-db:
    container_name: pcm-db
    image: mysql:5.7
    volumes:
      - pcm-db-data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=pcm
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "3306:3306"
  pcm-app:
    container_name: pcm-app
    build: .
    env_file: local.env
    volumes:
      - .:/var/www/html
    links:
      - pcm-db
    depends_on:
      - pcm-db
volumes:
  pcm-db-data:
